import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional, comprehensive PDF report for a cloud project.
 * @param {Object} project - The workspace/project data
 * @param {string} diagramImage - Base64 data URL of the architecture diagram (optional)
 */
export const generateProjectReport = async (project, diagramImage) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // Colors
    const primaryColor = [66, 133, 244]; // Cloudiverse Blue
    const secondaryColor = [80, 80, 80]; // Dark Gray
    const accentColor = [240, 240, 240]; // Light Gray background

    // Helper: Safe Data Access
    const state = project.state_json || {};
    const infraSpec = project.infraSpec || state.infraSpec || {};
    const costData = project.costEstimation || state.costEstimation || {};
    const requirements = infraSpec.requirements || {};
    const sizing = infraSpec.sizing || {};
    const domains = state.domain_mapping || infraSpec.domains || [];

    // Helper: Add Header
    const addHeader = (title = "Cloud Infrastructure Report") => {
        doc.setFillColor(...primaryColor);
        doc.rect(0, 0, pageWidth, 30, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text("CLOUDIVERSE", margin, 20);

        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(title, pageWidth - margin - doc.getTextWidth(title), 20);
    };

    // Helper: Add Footer (Marketing & Links)
    const addFooter = (pageNumber) => {
        const footerY = pageHeight - 15;

        doc.setDrawColor(200, 200, 200);
        doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("Generated by Cloudiverse AI - The Intelligent Cloud Architect", margin, footerY);

        const linkText = "www.cloudiverse.ai";
        doc.setTextColor(...primaryColor);
        doc.textWithLink(linkText, pageWidth - margin - doc.getTextWidth(linkText), footerY, { url: 'https://www.cloudiverse.ai' });

        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY, { align: 'center' });
    };

    // Helper: Check Page Break
    let yPos = 40;
    const checkPageBreak = (heightNeeded) => {
        if (yPos + heightNeeded > pageHeight - 30) {
            doc.addPage();
            addHeader();
            yPos = 40;
            return true;
        }
        return false;
    };

    // Helper: Section Title
    const addSectionTitle = (title) => {
        checkPageBreak(20);
        doc.setFontSize(16);
        doc.setTextColor(...secondaryColor);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, yPos);
        doc.setDrawColor(...primaryColor);
        doc.line(margin, yPos + 2, margin + doc.getTextWidth(title) + 5, yPos + 2); // Underline
        yPos += 15;
    };

    // --- PAGE 1: EXECUTIVE SUMMARY ---
    addHeader("Executive Summary");

    doc.setFontSize(24);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(project.name || 'Untitled Project', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    const desc = project.description || "Comprehensive cloud infrastructure architecture and cost analysis.";
    const descLines = doc.splitTextToSize(desc, pageWidth - (margin * 2));
    doc.text(descLines, margin, yPos);
    yPos += (descLines.length * 6) + 15;

    // Project Metadata Table
    const metaData = [
        ['Target Cloud', (state.selectedProvider || infraSpec.provider || 'Multi-Cloud').toUpperCase()],
        ['Region', infraSpec.resolved_region?.resolved || infraSpec.region || 'Auto-detected'],
        ['Environment', infraSpec.environment || 'Production'],
        ['Workload Type', (infraSpec.intent?.intent_classification?.workload_type || 'General').toUpperCase()],
        ['Traffic Tier', (sizing.tier || 'Medium').toUpperCase()],
        ['Date Generated', new Date().toLocaleDateString()]
    ];

    autoTable(doc, {
        startY: yPos,
        head: [['Key', 'Configuration']],
        body: metaData,
        theme: 'grid',
        headStyles: { fillColor: primaryColor, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 4 },
        columnStyles: { 0: { fontStyle: 'bold', width: 60 } },
        margin: { left: margin, right: margin }
    });
    yPos = doc.lastAutoTable.finalY + 15;

    // Requirements Snapshot
    addSectionTitle("Requirements & Specifications");

    const reqData = [];
    if (requirements.security_level) reqData.push(['Security Level', requirements.security_level]);
    if (requirements.compliance?.length) reqData.push(['Compliance', requirements.compliance.join(', ')]);
    if (requirements.availability_target) reqData.push(['Availability Target', requirements.availability_target]);
    if (requirements.data_residency) reqData.push(['Data Residency', 'Strict']);
    if (domains && domains.length > 0) {
        reqData.push(['Domains', domains.map(d => d.domain || d).join(', ')]);
    }

    if (reqData.length > 0) {
        autoTable(doc, {
            startY: yPos,
            body: reqData,
            theme: 'striped',
            styles: { fontSize: 10 },
            columnStyles: { 0: { fontStyle: 'bold', width: 60 } },
            margin: { left: margin, right: margin }
        });
        yPos = doc.lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        doc.text("No specific compliance or security constraints defined.", margin, yPos);
        yPos += 15;
    }

    // --- PAGE 2: ARCHITECTURE DIAGRAM ---
    doc.addPage();
    addHeader("Architecture Visualization");
    yPos = 40;

    if (diagramImage) {
        try {
            const imgProps = doc.getImageProperties(diagramImage);
            const pdfWidth = pageWidth - (margin * 2);
            const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

            // Check fit
            if (pdfHeight > pageHeight - 60) {
                // Scale to fit height
                const scaledHeight = pageHeight - 60;
                const scaledWidth = (imgProps.width * scaledHeight) / imgProps.height;
                const xCentered = margin + (pdfWidth - scaledWidth) / 2;
                doc.addImage(diagramImage, 'PNG', xCentered, yPos, scaledWidth, scaledHeight);
                yPos += scaledHeight + 10;
            } else {
                doc.addImage(diagramImage, 'PNG', margin, yPos, pdfWidth, pdfHeight);
                yPos += pdfHeight + 10;
            }

            doc.setFontSize(9);
            doc.setTextColor(100, 100, 100);
            doc.text("Figure 1: Generated System Architecture", pageWidth / 2, yPos, { align: 'center' });
            yPos += 15;
        } catch (e) {
            doc.text("[Diagram Rendering Error]", margin, yPos);
            yPos += 20;
        }
    } else {
        doc.text("[Architecture Diagram not available]", margin, yPos);
        yPos += 20;
    }

    // --- PAGE 3: COST ESTIMATION ---
    doc.addPage();
    addHeader("Cost Estimation Analysis");
    yPos = 40;

    // Cost Summary Box
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 40, 3, 3, 'F');

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("Estimated Monthly Cost", margin + 10, yPos + 15);

    doc.setFontSize(20);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    let costDisplay = "$0.00";
    if (costData.recommended && costData.recommended.formatted_cost) {
        costDisplay = costData.recommended.formatted_cost;
    } else if (costData.totalMonthlyCost) {
        costDisplay = costData.totalMonthlyCost;
    }
    doc.text(costDisplay, margin + 10, yPos + 30);
    yPos += 50;

    // Service Breakdown Table
    addSectionTitle("Service Cost Breakdown");

    // Attempt to gather service list with costs
    // Priority: costData.services -> costData.selected_services -> infraSpec.services
    let services = [];
    if (costData.services && Array.isArray(costData.services)) {
        services = costData.services;
    } else if (costData.provider_details) {
        // Try to extract from provider details
        const p = state.selectedProvider || infraSpec.provider || 'AWS';
        const details = costData.provider_details[p] || {};
        if (details.service_costs) {
            services = Object.entries(details.service_costs).map(([k, v]) => ({ name: k, cost: v }));
        }
    }

    if (services.length > 0) {
        const body = services.map(s => [
            s.name || s.service || 'Unknown',
            s.cost || s.price || '-',
            s.unit || 'Monthly'
        ]);

        autoTable(doc, {
            startY: yPos,
            head: [['Service Resource', 'Estimated Cost', 'Billing Unit']],
            body: body,
            theme: 'striped',
            headStyles: { fillColor: primaryColor },
            styles: { fontSize: 10 },
            margin: { left: margin, right: margin }
        });
        yPos = doc.lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        doc.text("Detailed service-level cost breakdown is available after deployment.", margin, yPos);
        yPos += 15;
    }

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    const disclaimer = "Disclaimer: These cost estimates are based on current cloud provider pricing and estimated usage patterns. Actual costs may vary based on data transfer, region, and specific workload behavior.";
    const discLines = doc.splitTextToSize(disclaimer, pageWidth - (margin * 2));
    doc.text(discLines, margin, yPos);


    // --- PAGE 4: SPECIFICATION & SERVICES ---
    doc.addPage();
    addHeader("Detailed Specifications");
    yPos = 40;

    addSectionTitle("Technical Stack & Services");

    const deployableServices = infraSpec.canonical_architecture?.deployable_services ||
        infraSpec.services_contract?.services || [];

    if (deployableServices.length > 0) {
        const specs = deployableServices.map(s => {
            const name = typeof s === 'string' ? s : (s.name || s.service_class);
            const type = getCategorization(name);
            const tier = (typeof s === 'object' && s.tier) ? s.tier : (sizing.tier || 'Standard');
            return [formatServiceName(name), type, tier];
        });

        autoTable(doc, {
            startY: yPos,
            head: [['Service Component', 'Category', 'Configuration Tier']],
            body: specs,
            theme: 'grid',
            headStyles: { fillColor: primaryColor },
            styles: { fontSize: 10 },
            margin: { left: margin, right: margin }
        });
    } else {
        doc.text("Standard Technical Stack Applied.", margin, yPos);
    }

    // Add Footers to all pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addFooter(i);
    }

    // Save
    doc.save(`${(project.name || 'Cloudiverse_Project').replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`);
};

// Helpers
function formatServiceName(key) {
    if (!key) return 'Unknown Service';
    const map = {
        'computecontainer': 'Container Service',
        'computeserverless': 'Serverless Functions',
        'apigateway': 'API Gateway',
        'relationaldatabase': 'Relational Database (SQL)',
        'nosqldatabase': 'NoSQL Database',
        'objectstorage': 'Object Storage',
        'cdn': 'Content Delivery Network',
        'loadbalancer': 'Load Balancer',
        'identityauth': 'Identity & Auth System'
    };
    return map[key.toLowerCase()] || key.charAt(0).toUpperCase() + key.slice(1);
}

function getCategorization(key) {
    if (!key) return 'General';
    const k = key.toLowerCase();
    if (k.includes('compute') || k.includes('container') || k.includes('function')) return 'Compute';
    if (k.includes('data') || k.includes('storage') || k.includes('sql')) return 'Storage';
    if (k.includes('gateway') || k.includes('cdn') || k.includes('balancer') || k.includes('dns')) return 'Network';
    return 'Application Integration';
}

